tasks:
  - init: npm install
    command: npm start

vscode:
  extensions:
    - RandomFractalsInc.vscode-data-preview@2.0.0:YHo7y4JxXqjNI4bb3wchiA==
    - donjayamanne.python-extension-pack@1.6.0:d2CAGx1tkZr49Mg/VZx4Hw==